platform :ios, "13.0"
use_frameworks! :linkage => :static

def pod_Common
  pod "JSCoreKit", :path => ".."
end

target "JSCoreKitExample" do
  pod_Common
  pod 'SwiftLint', :configurations => ['Debug']
  pod "LookinServer", :configurations => ["Debug"]
  pod "MLeaksFinder", :git => "https://github.com/Tencent/MLeaksFinder.git", :configurations => ["Debug"]
end
