platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'JSCoreKitExample' do
  pod 'JSCoreKit', :path => '..'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'MLeaksFinder', :configurations => ['Debug']
end


